### PR TITLE
add function to check for reverse pairs before friendship is created

### PR DESCRIPTION
**Pull request by kunmi02**
I created a function to avoid having duplicate friendship by making friend_id and user_id as the primary keys
I created a function to check for reverse pairs before a friendship is created

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑**

Hello team, 
Great work on the project. However your project is not working due to the error with gem 'composite_primary_keys'. Kindly fix it. However, as a review

[REQUESTED]: Kindly add integration tests as well.

Fix the errors and ask for another review
Happy coding💻

**Comment by kunmi02** [comment]
> ### **STATUS: CHANGES REQUESTED🛑🛑**
> Hello team,
> Great work on the project. However your project is not working due to the error with gem 'composite_primary_keys'. Kindly fix it. However, as a review
> 
> [REQUESTED]: Kindly add integration tests as well.
> 
> Fix the errors and ask for another review
> Happy coding💻

The  composite key gem is dependent on your ACTIVERECORD VERSION, Your active record gem needs to be greater that 5.0

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @kunmi02  ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**
- [x] From the previous milestone, you should be able to invite friends. right now, whenever i try to do so, I get the error below: 
image

- [ ] Remove all the commented-out codes from your models.
- [ ] When friendship is confirmed, an additional row with reversed user-friend pair is created. 
Thanks to this, we can find user friends only by user_id in the friendships table


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by Georjane — APPROVED** [review]
## Status: PR Approved 💯 🥇  
### Hi there Team ✋🏽 
Congratulations on successfully completing another milestone. Your project meets the minimum requirements for approval. It's a thumbs up for me. 👍🏽You can go ahead and merge this PR.🤝 

Good luck on your project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

**Pull request merged**
